### ISSUE TITLE
Convert rDoc readme to Markdown

### ISSUE THREAD

**Issue by hijonathan** [HubSpot/rHAPI#1]
Right now, it doesn't get formatted very nicely on the Open Source Projects page: http://github.hubspot.com/#rHAPI

We could either:
1. Convert the rdoc file to a markdown file.
2. Use [rdoc with the markdown syntax](https://github.com/rdoc/rdoc/blob/master/README.rdoc#writing-documentation).

**Comment by clp-jeremy** [comment]
Hi Jonathan,

I am open to either idea. I used rdoc since that was in use upstream 
when I forked it, but I enjoy using markdown.

How about we proceed with markdown?

-Jeremy

**Comment by hijonathan** [comment]
That was quick. Nice job :+1:

**Comment by clp-jeremy** [comment]
Thanks -- I noticed we will want to update the install instructions, as rubygems.org hosts the original version.
