### ISSUE TITLE
JSON dependency is over three years old

### ISSUE THREAD

**Issue by digerata** [HubSpot/rHAPI#9]
Attempting to bring this library into an existing codebase and I get a conflict when gem installing:

```
Bundler could not find compatible versions for gem "json":
  In Gemfile:
    r_hapi (>= 0) ruby depends on
      json (~> 1.5.1) ruby

paperclip (>= 0) ruby depends on
  json (1.8.1)
```

So checking up on this, it appears the json gem requested is over three years old.  Json is a pretty common gem.  It seems a more recent or a more flexible version dependency would be helpful here.

**Comment by digerata** [comment]
Okay, never mind.  The version of rHAPI in ruby gems is not the same as this repo.  It might make sense to update the readme to specify :git => 'https://github.com/HubSpot/rHAPI.git'

**Comment by nicobrenner** [comment]
Thank you @digerata. Just ran into the same problem. Your suggestion worked, however now curb won't compile (https://github.com/taf2/curb/issues/234).

Are you still using this gem or did you move onto something else for integrating with Hubspot?

**Comment by digerata** [comment]
I actually switched to the hubspot-ruby gem. It's pretty bad when third party code works better than first party.

**Comment by nicobrenner** [comment]
@digerata thank you for your quick reply! You are totally right.

Unfortunately hubspot-ruby doesn't support oauth.

There's this fork with updated gemspec though: https://github.com/matholroyd/rHAPI by @matholroyd
